"""
Hypernymy Task Specification

Thin wrapper for hypernymy word relations task.
Supports EAP, EAP-IG, and IBCircuit algorithms.
"""

from functools import partial
from pathlib import Path
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional, Tuple

if TYPE_CHECKING:
    from torch.utils.data import DataLoader

import torch

from ...data.eap_dataset import EAPDiscoveryDataset
from ...data.task_data.tasks.hypernymy.utils import generate_hypernymy_data
from ...utils.logging import get_logger
from .._algorithm_families import (
    CDT_FAMILY,
    EAP_FAMILY,
    IB_FAMILY,
    is_eap_family,
    unsupported_algorithm_message,
)
from .._chat import resolve_chat_template
from ..specs import _find_task_cache, _load_finetuning_data_from_csv

logger = get_logger("task.hypernymy")


class HypernymyTaskSpec:
    """Hypernymy task using simplified wrapper approach."""

    name = "hypernymy"
    pair_padding_side = "right"
    # diagnostic minimal-pair task -- discovered raw, per the circuit-discovery literature
    chat_template_mode: str = "off"

    def validate_discovery_config(self, discovery_cfg: Dict[str, Any]) -> None:
        """Validate Hypernymy-specific discovery configuration."""
        algorithm = discovery_cfg.get("algorithm", "").lower()
        if algorithm not in (EAP_FAMILY | IB_FAMILY | CDT_FAMILY):
            raise ValueError(
                unsupported_algorithm_message(
                    "Hypernymy", algorithm, EAP_FAMILY | IB_FAMILY | CDT_FAMILY
                )
            )

        level = discovery_cfg.get("level")
        if level not in ["node", "neuron"]:
            raise ValueError(
                f"Hypernymy discovery config has invalid 'level': {level!r}. "
                f"Set discovery config key 'level' to 'node' or 'neuron'."
            )

        if algorithm == "ibcircuit":
            scope = discovery_cfg.get("scope", "heads")
            if scope not in ["heads", "mlp", "both"]:
                raise ValueError(
                    f"Hypernymy ibcircuit has invalid 'scope': {scope!r}. "
                    f"Set discovery config key 'scope' to one of: heads, mlp, both."
                )

        batch_size = discovery_cfg.get("batch_size", 4)
        if not isinstance(batch_size, int) or batch_size <= 0:
            raise ValueError(
                f"Hypernymy has invalid 'batch_size': {batch_size!r}. "
                f"Set discovery config key 'batch_size' to a positive integer (e.g. 4)."
            )

    def build_dataloader(
        self,
        model,
        discovery_cfg: Dict[str, Any],
        device: str,
    ) -> "DataLoader":
        """Build DataLoader for Hypernymy task."""
        if model is None:
            raise ValueError("Hypernymy task requires model for tokenizer.")

        # Hypernymy prompts are generated by an external data module and the
        # EAP dataloader tokenizes the cached CSV internally -- there is no
        # single prompt-string finalization point this task spec can wrap
        # without a fragile rewrite. Default "off" keeps everything raw; an
        # explicit override fails loudly rather than being silently ignored.
        mode = discovery_cfg.get("chat_template_mode", self.chat_template_mode)
        apply = resolve_chat_template(mode, model)
        if apply:
            raise NotImplementedError(
                f"{self.name}: this diagnostic task is discovered on raw "
                f"(non-chat-templated) prompts and does not support a "
                f"chat_template_mode override that enables templating. "
                f"Remove the 'chat_template_mode' key from the discovery "
                f"config or set it to 'off'."
            )

        algorithm = discovery_cfg.get("algorithm", "").lower()

        if algorithm == "ibcircuit":
            return self._build_ibcircuit_dataloader(discovery_cfg, device, model)
        elif is_eap_family(algorithm) or algorithm == "cdt":
            return self._build_eap_dataloader(discovery_cfg, device, model)
        else:
            raise ValueError(
                unsupported_algorithm_message(
                    "Hypernymy", algorithm, EAP_FAMILY | IB_FAMILY | CDT_FAMILY
                )
            )

    def _get_or_generate_csv(self, discovery_cfg: Dict[str, Any], model) -> Path:
        """Return path to cached Hypernymy CSV, generating it if absent."""
        data_params = discovery_cfg.get("data_params", {})
        n_samples = data_params.get("num_examples", data_params.get("n_samples", 128))
        seed = data_params.get("seed", 42)
        cache_dir = Path(discovery_cfg.get("cache_dir", "./cache/hypernymy"))
        cache_dir.mkdir(parents=True, exist_ok=True)

        model_name = getattr(model.cfg, "model_name", "unknown").replace("/", "_")
        data_path = cache_dir / f"hypernymy_{model_name}_{n_samples}_seed{seed}.csv"

        if not data_path.exists():
            generate_hypernymy_data(
                n_samples=n_samples,
                output_path=str(data_path),
                seed=seed,
                model=model,
            )
        return data_path

    def _build_eap_dataloader(
        self, discovery_cfg: Dict[str, Any], device: str, model
    ) -> "DataLoader":
        """Build EAP/EAP-IG DataLoader."""
        data_path = self._get_or_generate_csv(discovery_cfg, model)
        batch_size = discovery_cfg.get("batch_size", 4)
        side = discovery_cfg.get("pair_padding_side", self.pair_padding_side)
        logger.debug(
            f"[DEBUG PADDING] hypernymy EAP dataloader  pair_padding_side='{side}'  batch_size={batch_size}"
        )
        return EAPDiscoveryDataset(data_path).to_dataloader(batch_size, pair_padding_side=side)

    def _build_ibcircuit_dataloader(self, discovery_cfg: Dict[str, Any], device: str, model):
        """Build fixed-batch DataLoader for IBCircuit."""
        import pandas as pd

        data_path = self._get_or_generate_csv(discovery_cfg, model)
        df = pd.read_csv(str(data_path))
        clean_texts = df["clean"].tolist()
        correct_idxs = df["correct_idx"].tolist()

        # Tokenize each prompt individually
        token_lists = [
            model.to_tokens(text, prepend_bos=True).squeeze(0).cpu() for text in clean_texts
        ]

        # answer_position = last real token
        answer_positions_list = [toks.shape[0] - 1 for toks in token_lists]

        # Right-pad to uniform length
        max_len = max(toks.shape[0] for toks in token_lists)
        pad_id = getattr(model.tokenizer, "pad_token_id", None)
        if pad_id is None:
            pad_id = getattr(model.tokenizer, "eos_token_id", None) or 0

        padded = []
        for toks in token_lists:
            gap = max_len - toks.shape[0]
            if gap > 0:
                toks = torch.cat([toks, torch.full((gap,), pad_id, dtype=torch.long)])
            padded.append(toks)

        tokens = torch.stack(padded).to(device)
        labels = torch.tensor(correct_idxs, dtype=torch.long, device=device)
        answer_positions = torch.tensor(answer_positions_list, dtype=torch.long, device=device)

        batch = {
            "tokens": tokens,
            "labels": labels,
            "answer_positions": answer_positions,
        }

        logger.debug(
            f"[DEBUG PADDING] hypernymy IBCircuit  within-batch=right-padded  max_len={max_len}  answer_pos range=[{answer_positions.min().item()}, {answer_positions.max().item()}]"
        )

        class SingleBatchDataLoader:
            """Yields one fixed batch repeatedly."""

            def __init__(self, batch):
                self.batch = batch

            def __iter__(self):
                yield self.batch

        return SingleBatchDataLoader(batch)

    def build_finetuning_dataset(
        self,
        tokenizer,
        model_name: str,
        n_examples: int,
        discovery_cfg: Optional[Dict[str, Any]] = None,
        seed: int = 42,
    ) -> Tuple[List[str], List[str]]:
        """Load Hypernymy finetuning data from discovery cache."""
        cfg = discovery_cfg or {}
        model_name_safe = model_name.replace("/", "_")
        cache_dir = Path(cfg.get("cache_dir", "./cache/hypernymy"))

        cache_path = _find_task_cache(cache_dir, self.name, model_name_safe)
        if cache_path is None:
            raise FileNotFoundError(
                f"No '{self.name}' cache found for model '{model_name}' "
                f"in {cache_dir}.\n"
                f"Run discover_circuit with task='{self.name}' first."
            )
        return _load_finetuning_data_from_csv(cache_path, tokenizer, n_examples, seed)

    def metric_fn(self, metric_type: str = "prob") -> Callable:
        """Return metric function for circuit discovery."""
        if metric_type == "kl":
            return partial(self._kl_divergence, loss=True, mean=True)
        return partial(self._prob_metric, loss=True, mean=True)

    @staticmethod
    def _prob_metric(logits, clean_logits, input_length, labels, mean=True, loss=False):
        """Probability of correct hypernym."""
        import torch as t

        batch_size = logits.size(0)
        idx = t.arange(batch_size, device=logits.device)
        probs = t.softmax(logits[idx, input_length - 1], dim=-1)
        results = t.gather(probs, -1, labels[:, 0:1].to(logits.device)).squeeze(-1)
        if loss:
            results = -results
        if mean:
            results = results.mean()
        return results

    @staticmethod
    def _kl_divergence(logits, clean_logits, input_length, labels, mean=True, loss=False):
        """KL divergence between patched and clean distributions."""
        import torch.nn.functional as F

        return F.kl_div(
            F.log_softmax(logits, dim=-1),
            F.softmax(clean_logits, dim=-1),
            reduction="batchmean",
        )

    def artifact_metadata(self, discovery_cfg: Dict[str, Any]) -> Dict[str, Any]:
        """Generate metadata for Hypernymy artifacts."""
        return {
            "task": "hypernymy",
            "data_source": "built_in_generation",
            "algorithm": discovery_cfg.get("algorithm"),
            "level": discovery_cfg.get("level"),
            "n_samples": discovery_cfg.get("data_params", {}).get("n_samples", 128),
            "chat_template_mode": discovery_cfg.get("chat_template_mode", self.chat_template_mode),
        }
