import random
from dataclasses import dataclass
from typing import Dict, List, Optional, Union  # <--- FIX: Added Optional here

import torch
from transformer_lens import HookedTransformer

# Adapted from the ACDC repository, acdc/docstring/prompts.py:
# https://github.com/ArthurConmy/Automatic-Circuit-Discovery (MIT). See THIRD_PARTY_LICENSES.md.

import logging

logger = logging.getLogger(__name__)

variable_names = "data name file value test new result line user key default request path output node item url model response text version function log string field start number values sub index error current context image message check json create size event state row obj parser end files form query fields instance label run action target array code num table source msg config first required options ret update module status group content client filename results last read command val base format color settings order found count match tag title parent call session token server host date description mode expected project info valid page header option task shape load names port old resource root".split(
    " "
)
common_single_token_nouns = [
    "price",
    "control",
    "action",
    "cost",
    "issue",
    "process",
    "position",
    "course",
    "minute",
    "education",
    "type",
    "research",
    "subject",
    "girl",
    "age",
    "father",
    "force",
    "order",
    "value",
    "act",
    "matter",
    "health",
    "lot",
    "street",
    "patient",
    "class",
    "mind",
    "church",
    "condition",
    "paper",
    "bank",
    "century",
    "section",
    "activity",
    "table",
    "building",
    "sense",
    "sort",
    "staff",
    "team",
    "student",
    "language",
    "town",
    "plan",
    "management",
    "morning",
    "committee",
    "product",
    "practice",
    "evidence",
    "ground",
    "letter",
    "foot",
    "boy",
    "back",
    "game",
    "food",
    "union",
    "role",
    "event",
    "land",
    "art",
    "support",
    "range",
    "stage",
    "trade",
    "voice",
    "arm",
    "club",
    "field",
    "history",
    "parent",
    "account",
    "material",
    "care",
    "manager",
    "project",
    "record",
    "example",
    "training",
    "window",
    "air",
    "light",
    "wife",
    "quality",
    "rule",
    "pound",
    "story",
    "tax",
    "worker",
    "data",
    "model",
    "nature",
    "bed",
    "hospital",
    "method",
    "unit",
    "detail",
    "date",
    "wall",
    "computer",
    "amount",
    "bit",
    "president",
    "chapter",
    "property",
    "son",
    "director",
    "leader",
    "south",
    "application",
    "board",
    "king",
    "production",
    "operation",
    "share",
    "lord",
    "contract",
    "picture",
    "test",
    "security",
    "election",
    "source",
    "colour",
    "future",
    "site",
    "loss",
    "shop",
    "animal",
    "heart",
    "purpose",
    "standard",
    "page",
    "doctor",
    "factor",
    "hair",
    "love",
    "music",
    "charge",
    "pattern",
    "design",
    "piece",
    "population",
    "tree",
    "knowledge",
    "performance",
    "plant",
    "pressure",
    "fire",
    "environment",
    "size",
    "analysis",
    "rest",
    "success",
    "thought",
    "region",
    "list",
    "relation",
    "set",
    "space",
    "statement",
    "demand",
    "sea",
    "step",
    "capital",
    "choice",
    "player",
    "station",
    "film",
    "feature",
    "income",
    "individual",
    "cup",
    "technology",
    "machine",
    "cell",
    "degree",
    "energy",
    "growth",
    "treatment",
    "mile",
    "function",
    "risk",
    "sound",
    "task",
    "top",
    "resource",
    "floor",
    "science",
    "style",
    "hall",
    "horse",
    "response",
    "character",
    "user",
    "answer",
    "dog",
    "look",
    "brother",
    "argument",
    "season",
    "bill",
    "element",
    "glass",
    "duty",
    "claim",
    "fund",
    "leg",
    "park",
    "title",
    "note",
    "daughter",
    "sun",
    "box",
    "river",
    "profit",
    "division",
    "stone",
    "post",
    "client",
    "help",
    "image",
    "oil",
    "sector",
    "attack",
    "direction",
    "seat",
    "employment",
    "goal",
    "sign",
    "ability",
    "campaign",
    "fish",
    "item",
    "medium",
    "show",
    "version",
    "drug",
    "library",
    "press",
    "surface",
    "blood",
    "culture",
    "memory",
    "return",
    "bar",
    "talk",
    "access",
    "deal",
    "star",
    "text",
    "cause",
    "mouth",
    "payment",
    "context",
    "reference",
    "second",
    "article",
    "chair",
    "earth",
    "object",
    "agency",
    "card",
    "collection",
    "communication",
    "public",
    "document",
    "weight",
    "bird",
    "rock",
    "call",
    "edge",
    "miss",
    "option",
    "quarter",
    "stock",
    "aid",
    "concept",
    "match",
    "network",
    "radio",
    "target",
    "finger",
    "forest",
    "race",
    "sex",
    "ball",
    "crime",
    "message",
    "peace",
    "review",
    "scale",
    "scene",
    "speech",
    "band",
    "expression",
    "hill",
    "reader",
    "owner",
    "trust",
    "truth",
    "turn",
    "file",
    "past",
    "start",
    "trial",
    "balance",
    "copy",
    "league",
    "length",
    "wind",
    "front",
    "move",
    "pain",
    "spirit",
    "train",
    "contact",
    "official",
    "strength",
    "cash",
    "gas",
    "shape",
    "agent",
    "pair",
    "protection",
    "rise",
    "driver",
    "master",
    "meaning",
    "vote",
    "adult",
    "play",
    "fig",
    "route",
    "speed",
    "credit",
    "impact",
    "danger",
    "flower",
    "half",
    "path",
    "track",
    "video",
    "aim",
    "bag",
    "comment",
    "content",
    "distance",
    "gold",
    "link",
    "skin",
    "boat",
    "dad",
    "prison",
    "sight",
    "wine",
    "offer",
    "writer",
    "hole",
    "package",
    "confidence",
    "generation",
    "key",
    "phone",
    "sample",
    "ship",
    "threat",
    "volume",
    "author",
    "background",
    "engine",
    "entry",
    "stuff",
    "yard",
    "bus",
    "regulation",
    "row",
    "song",
    "category",
    "consumer",
    "football",
    "meal",
    "wood",
    "bridge",
    "description",
    "existence",
    "flat",
    "lip",
    "session",
    "sheet",
    "code",
    "flight",
    "limit",
    "plate",
    "rain",
    "respect",
    "writing",
    "capacity",
    "dream",
    "selection",
    "spring",
    "while",
    "definition",
    "egg",
    "examination",
    "mark",
    "notice",
    "output",
    "will",
    "address",
    "bottom",
    "kid",
    "middle",
    "neck",
    "run",
    "acid",
    "assembly",
    "birth",
    "ear",
    "error",
    "module",
    "store",
    "transfer",
    "wave",
    "channel",
    "component",
    "cut",
    "fee",
    "lead",
    "weather",
    "block",
    "brain",
    "guide",
    "program",
    "screen",
    "connection",
    "cover",
    "map",
    "metal",
    "phase",
    "pool",
    "search",
    "sequence",
    "sky",
    "sum",
    "trip",
    "cat",
    "display",
    "gallery",
    "gate",
    "heat",
    "location",
    "reading",
    "theme",
    "drive",
    "faith",
    "hell",
    "learning",
    "opening",
    "priority",
    "spot",
    "tool",
    "castle",
    "coal",
    "flow",
    "lane",
    "motion",
    "release",
    "total",
    "wing",
    "border",
    "index",
    "pocket",
    "ring",
    "billion",
    "device",
    "engineering",
    "fruit",
    "lake",
    "leaf",
    "pub",
    "request",
    "square",
    "tone",
    "walk",
    "chain",
    "circle",
    "creation",
    "fall",
    "present",
    "shot",
    "fashion",
    "god",
    "mass",
    "panel",
    "fan",
    "iron",
    "origin",
    "ticket",
    "bone",
    "cancer",
    "chief",
    "editor",
    "fuel",
    "general",
    "height",
    "round",
    "vision",
    "warning",
    "being",
    "cross",
    "living",
    "rail",
    "working",
    "column",
    "finding",
    "gap",
    "grass",
    "plane",
    "root",
    "score",
    "shadow",
    "shock",
    "touch",
    "database",
    "formation",
    "male",
    "ref",
    "resident",
    "resolution",
    "topic",
    "break",
    "camp",
    "currency",
    "phrase",
    "thinking",
    "coat",
    "mill",
    "stress",
    "boot",
    "command",
    "depth",
    "female",
    "frame",
    "framework",
    "holder",
    "ice",
    "inch",
    "port",
    "protein",
    "rose",
    "saving",
    "string",
    "wheel",
    "bishop",
    "cycle",
    "export",
    "hat",
    "load",
    "mode",
    "setting",
    "stairs",
    "travel",
    "average",
    "camera",
    "focus",
    "green",
    "guard",
    "input",
    "layer",
    "poll",
    "sleep",
    "suit",
    "bread",
    "cake",
    "efficiency",
    "peak",
    "self",
    "angle",
    "bay",
    "bid",
    "cloud",
    "custom",
    "dollar",
    "variable",
    "zone",
    "actor",
    "chip",
    "core",
    "final",
    "frequency",
    "gain",
    "guy",
    "relative",
    "rent",
    "reply",
    "secret",
    "shirt",
    "apple",
    "instance",
    "intelligence",
    "lad",
    "pipe",
    "anger",
    "disk",
    "fight",
    "hero",
    "journal",
    "left",
    "mail",
    "pace",
    "paragraph",
    "platform",
    "print",
    "rank",
    "sand",
    "scope",
    "shift",
    "stream",
    "chemical",
    "clock",
    "delay",
    "host",
    "human",
    "count",
    "mission",
    "pack",
    "seed",
    "tail",
    "tie",
    "watch",
    "dark",
    "hold",
    "mine",
    "net",
    "tip",
    "dimension",
    "operator",
    "professional",
    "shell",
    "storage",
    "summary",
    "tube",
    "conduct",
    "determination",
    "drop",
    "import",
    "label",
    "percent",
    "pot",
    "proof",
    "unity",
    "win",
    "wire",
    "bell",
    "comfort",
    "complex",
    "draft",
    "grade",
    "lift",
    "mouse",
    "movie",
    "profile",
    "standing",
    "belt",
    "black",
    "check",
    "joy",
    "local",
    "pit",
    "red",
    "register",
    "storm",
    "album",
    "ban",
    "bench",
    "button",
    "cap",
    "chart",
    "coin",
    "dust",
    "folk",
    "margin",
    "pole",
    "stand",
    "stick",
    "tin",
]


@dataclass
class Prompt:
    clean_prompt: str
    corrupt_prompt: Union[str, Dict[str, str]]
    correct_answers: List[str]
    wrong_answers: List[str]


class BatchedPrompts:
    def __init__(self, prompts: List[Prompt], model: HookedTransformer):
        self.clean_prompt = [p.clean_prompt for p in prompts]
        if isinstance(prompts[0].corrupt_prompt, str):
            self.corrupt_prompt = [p.corrupt_prompt for p in prompts]
        else:
            self.corrupt_prompt = {
                key: [p.corrupt_prompt[key] for p in prompts]
                for key in prompts[0].corrupt_prompt.keys()
            }
        self.correct_answers = [p.correct_answers for p in prompts]
        if self.correct_answers[0][0][0] != " ":
            logger.info("THE CORRECT ANSWER DOES NOT START WITH A SPACE -- ARE YOU SURE ABOUT THAT?")
        self.wrong_answers = [p.wrong_answers for p in prompts]

        self.clean_tokens = torch.stack(
            [model.to_tokens(batch, prepend_bos=True)[0] for batch in self.clean_prompt]
        )
        if isinstance(prompts[0].corrupt_prompt, str):
            self.corrupt_tokens = torch.stack(
                [model.to_tokens(batch, prepend_bos=True)[0] for batch in self.corrupt_prompt]
            )
        else:
            self.corrupt_tokens = {
                key: torch.stack([model.to_tokens(batch, prepend_bos=True)[0] for batch in prompts])
                for key, prompts in self.corrupt_prompt.items()
            }

        self.correct_tokens = torch.stack(
            [model.to_tokens(batch, prepend_bos=False)[:, 0] for batch in self.correct_answers]
        )
        self.wrong_tokens = torch.stack(
            [model.to_tokens(batch, prepend_bos=False)[:, 0] for batch in self.wrong_answers]
        )


def docstring_prompt_templ(
    style: str,
    *,
    met_name: str,
    met_desc_words: List[str],
    def_args: List[str],
    doc_args: List[str],
    doc_args_desc_words: List[List[str]],
    default: bool = False,
) -> str:
    def_args_str = ", ".join(arg + ("=None" if default else "") for arg in def_args)
    met_desc_str = " ".join(met_desc_words)
    ind4 = 4 * " "
    args_line = (
        f"""
{ind4}Args:"""
        if style == "goog"
        else ""
    )
    def_and_desc = f'''def {met_name}(self, {def_args_str}):
{ind4}"""{met_desc_str}
{args_line}'''
    param_prefix = f"{ind4}:param" if style == "rest" else f"{ind4}    "
    doc_args_desc = [" ".join(arg_desc_words) for arg_desc_words in doc_args_desc_words]
    doc_lines = [f"{param_prefix} {arg}: {desc}" for arg, desc in zip(doc_args, doc_args_desc)]
    doc_lines_str = "\n".join(doc_lines)
    return f"""
{def_and_desc}
{doc_lines_str}
{param_prefix}"""


def docstring_prompt_gen(
    style: str,  # rest or goog,
    *,
    n_args: int,  # num of args in method def
    pred_nth_arg: Optional[int] = None,  # arg index to predict, last if None
    met_desc_len: int = 10,  # number of words in first doc line
    arg_desc_len: int = 4,  # number of words in each arg desc
    seed: int = 42,
) -> Prompt:
    random.seed(seed)
    assert style in ["rest", "goog"]
    if pred_nth_arg is None:
        pred_nth_arg = n_args - 1

    met_name, *def_args = random.sample(variable_names, 1 + n_args)
    clean_doc_args = def_args[:pred_nth_arg]
    met_desc_words = random.sample(common_single_token_nouns, met_desc_len)
    doc_args_desc_words = [
        random.sample(common_single_token_nouns, arg_desc_len) for _ in clean_doc_args
    ]

    clean_prompt = docstring_prompt_templ(
        style,
        met_name=met_name,
        met_desc_words=met_desc_words,
        def_args=def_args,
        doc_args=clean_doc_args,
        doc_args_desc_words=doc_args_desc_words,
    )

    correct_answers = [" " + def_args[pred_nth_arg]]
    wrong_answers = [" " + arg for arg in def_args if arg != def_args[pred_nth_arg]]

    # Generate a single type of corruption: shuffle the documented arguments
    shuffled_doc_args = list(clean_doc_args)
    while shuffled_doc_args == clean_doc_args:
        random.shuffle(shuffled_doc_args)

    corrupt_prompt = docstring_prompt_templ(
        style,
        met_name=met_name,
        met_desc_words=met_desc_words,
        def_args=def_args,
        doc_args=shuffled_doc_args,
        doc_args_desc_words=doc_args_desc_words,
    )

    return Prompt(
        clean_prompt=clean_prompt,
        corrupt_prompt={"random_doc": corrupt_prompt},  # Use a dictionary for consistency
        correct_answers=correct_answers,
        wrong_answers=wrong_answers,
    )
